package com.gemini.reporting.summary;

import com.gemini.reporting.excel.ExecutionSummaryExcelGenerator;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.Duration;
import java.time.LocalDateTime;

public class ExecutionSummaryManager {

    private static LocalDateTime startTime;
    private static LocalDateTime endTime;

    private static int totalTests;
    private static int passedTests;
    private static int failedTests;
    private static int skippedTests;

    private static String framework;
    private static String reportType;
    private static String os;
    private static String javaVersion;

    public static void setFramework(String framework) {
        ExecutionSummaryManager.framework = framework;
    }

    public static void startExecution() {

        startTime = LocalDateTime.now();

        totalTests = 0;
        passedTests = 0;
        failedTests = 0;
        skippedTests = 0;

        if (framework == null || framework.isBlank()) {
            framework = "TestNG";
        }

        reportType = System.getProperty("reportType");

        if (reportType == null || reportType.isBlank()) {
            reportType = "Extent";
        }

        os = System.getProperty("os.name");
        javaVersion = System.getProperty("java.version");
    }

    public static void testPassed() {
        totalTests++;
        passedTests++;
    }

    public static void testFailed() {
        totalTests++;
        failedTests++;
    }

    public static void testSkipped() {
        totalTests++;
        skippedTests++;
    }

    public static void finishExecution() {
        endTime = LocalDateTime.now();
    }

    public static void generateSummary() {

        try {

            File folder = new File("reports");

            if (!folder.exists()) {
                folder.mkdirs();
            }

            Duration duration = Duration.between(startTime, endTime);

            long seconds = duration.toSeconds();
            long minutes = seconds / 60;
            seconds = seconds % 60;

            double passPercentage = 0;

            if (totalTests != 0) {
                passPercentage = (passedTests * 100.0) / totalTests;
            }

            try (FileWriter writer =
                         new FileWriter("reports/ExecutionSummary.txt")) {

                writer.write("=============================================\n");
                writer.write("              GEM REPORTING\n");
                writer.write("           EXECUTION SUMMARY\n");
                writer.write("=============================================\n\n");

                writer.write("Execution Date : " + startTime.toLocalDate() + "\n");
                writer.write("Start Time     : " + startTime.toLocalTime() + "\n");
                writer.write("End Time       : " + endTime.toLocalTime() + "\n");
                writer.write("Duration       : "
                        + minutes + " min "
                        + seconds + " sec\n\n");

                writer.write("---------------------------------------------\n");

                writer.write("Framework      : " + framework + "\n");
                writer.write("Report Type    : " + reportType + "\n");
                writer.write("Operating Sys. : " + os + "\n");
                writer.write("Java Version   : " + javaVersion + "\n\n");

                writer.write("---------------------------------------------\n");

                writer.write("Total Tests    : " + totalTests + "\n");
                writer.write("Passed         : " + passedTests + "\n");
                writer.write("Failed         : " + failedTests + "\n");
                writer.write("Skipped        : " + skippedTests + "\n");

                writer.write("Pass Percentage: "
                        + String.format("%.2f", passPercentage)
                        + " %\n");

                writer.write("\n---------------------------------------------\n");
                writer.write("Generated By GemReporting\n");
                writer.write("=============================================\n");
            }

            // Generate Excel Summary
            ExecutionSummaryExcelGenerator.generate();

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    // =========================
    // Getters
    // =========================

    public static LocalDateTime getStartTime() {
        return startTime;
    }

    public static LocalDateTime getEndTime() {
        return endTime;
    }

    public static int getTotalTests() {
        return totalTests;
    }

    public static int getPassedTests() {
        return passedTests;
    }

    public static int getFailedTests() {
        return failedTests;
    }

    public static int getSkippedTests() {
        return skippedTests;
    }

    public static String getFramework() {
        return framework;
    }

    public static String getReportType() {
        return reportType;
    }

    public static String getOs() {
        return os;
    }

    public static String getJavaVersion() {
        return javaVersion;
    }
}